services:
  web:
    network_mode: "host"
    build: .
    environment:
      VIRTUAL_HOST: jstet.net
    expose:
       - 80
    restart: always

networks:
  default:
    external:
      name: nginx-proxy