services:
  web:
    build: .
    environment:
      - LETSENCRYPT_HOST=jstet.net
      - VIRTUAL_HOST=jstet.net
      - VIRTUAL_PORT=8080

    restart: always
    networks:
    - nginx-proxy_proxy
    - default
networks:
  nginx-proxy_proxy:
    external: true

