version: "3.9"
services:
  web:
    build: .
    network_mode: "host"
    environment:
      VIRTUAL_HOST: jstet.net
    expose:
       - 5000

networks:
  default:
    external:
      name: nginx-proxy