services:
  web:
    build: .
    environment:
      - LETSENCRYPT_HOST=jstet.net
      - VIRTUAL_HOST=jstet.net
    restart: always
    networks:
    - frontproxy_default
    - default
    networks:
      frontproxy_default:
        external: true

