name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}d
          script: |
            cd homepage
            git reset --hard
            git pull origin main
            docker build --no-cache -t jstet/homepage:latest .
            docker push jstet/homepage:latest
            cd ../compose_homepage
            docker stack deploy -c docker-compose.yml homepage
